MVCTutorial/MVCTutorial.Web/Models/Department.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVCTutorial.Web.Models
{
    [Table("tblDepartment")]
    public class Department
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(10)]
        public string DepartmentName { get; set; }
        public string Location { get; set; }
        public string DepartmentHead { get; set; }

        // nagivation property
        public ICollection<Employee> Employees { get; set; }
    }
}

MVCTutorial/MVCTutorial.Web/Controllers/DepartmentController.cs
using MVCTutorial.Web.Models;
using MVCTutorial.Web.ProjectDbContext;
using System;
using System.Linq;
using System.Web.Mvc;

namespace MVCTutorial.Web.Controllers
{
    public class DepartmentController : Controller
    {
        // GET: Department List View
        public ActionResult Index()
        {
            using (var dbContext = new MyDbContext())
            {
                // 在List View不显示员工信息，所以我们不使用Include("Employees")
                var departments = dbContext.Departments.ToList();
                return View(departments);
            }
        }

        // GET: Department Detail View
        public ActionResult Details(int id)
        {
            using (var dbContext = new MyDbContext())
            {
                // 根据传入的departmentId, 查找一个特定的department，包含它的Employees，建立一个ViewModel
                // 给你departmentId, 帮我寻找第一个满足条件的department记录
                var department = dbContext.Departments
                                           .Include("Employees")
                                           .FirstOrDefault(dept => dept.Id == id);
                
                return View(department);
            }
        }

        // GET 生成Create的页面
        public ActionResult Create()
        {
            return View();
        }

        // POST 实际接受表单传递过来的数据
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Department department)
        {
            // 检查传入的department对象是否符合要求
            if (!ModelState.IsValid)
            {
                // 如果不符合，则带着错误信息，返回到Edit View
                return View(department);
            }

            using (var dbContext = new MyDbContext())
            {
                // 将新的记录加入到之前已有的记录当中去
                dbContext.Departments.Add(department);

                // 保存到
                dbContext.SaveChanges();

                // 告诉Entity Framework 将新纪录存入数据库
                return RedirectToAction("Index");
            }
        }

        // GET Edit View
        public ActionResult Edit(int id)
        {
            using (var dbContext = new MyDbContext())
            {
                // 根据传入的departmentId, 查找一个特定的department，包含它的Employees，建立一个ViewModel
                // 给你departmentId, 帮我寻找第一个满足条件的department记录
                var department = dbContext.Departments
                                           .Include("Employees")
                                           .FirstOrDefault(dept => dept.Id == id);

                return View(department);
            }
        }

        // 实现增删改查的“改”
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Department department)
        {
            // 检查传入的department对象是否符合要求
            if (!ModelState.IsValid)
            {
                // 如果不符合，则带着错误信息，返回到Edit View
                return View(department);
            }

            using (var dbContext = new MyDbContext())
            {
                // 根据传入的departmentId, 查找一个特定的department，包含它的Employees，建立一个ViewModel
                // 给你departmentId, 帮我寻找第一个满足条件的department记录
                var departmentInDb = dbContext.Departments
                                           .Include("Employees")
                                           .FirstOrDefault(dept => dept.Id == department.Id);

                // 如果在数据库中找到了对应的记录，则进行下面的操作，即将传入的新的department数据，赋值给数据库中对应的记录
                if (departmentInDb != null)
                {
                    departmentInDb.DepartmentName = department.DepartmentName;
                    departmentInDb.Location = department.Location;
                    departmentInDb.DepartmentHead = department.DepartmentHead;
                    // 告诉Entity Framework 将新纪录存入数据库
                    dbContext.SaveChanges();
                }
                // 返回到Details View
                return RedirectToAction("Index");
            }
        }

        // 实现增删改查的“删”
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id = 0)
        {
            // 检查传入的department对象是否符合要求
            if (id == 0)
            {
                throw new Exception("Invalid request");
            }

            using (var dbContext = new MyDbContext())
            {
                var departmentInDb = dbContext.Departments
                                           .Include("Employees")
                                           .FirstOrDefault(dept => dept.Id == id);

                // 如果在数据库中找到了对应的记录，则进行下面的操作，即将传入的新的department数据，赋值给数据库中对应的记录
                if (departmentInDb != null)
                {
                    dbContext.Departments.Remove(departmentInDb);
                    // 告诉Entity Framework 将新纪录存入数据库
                    dbContext.SaveChanges();
                }
                // 返回到Details View
                return RedirectToAction("Index");
            }
        }

        #region 演示不同的modelBinding的方法

        //// 实现增删改查的“改”
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(FormCollection department)
        //{
        //    using (var dbContext = new MyDbContext())
        //    {
        //        // 根据传入的departmentId, 查找一个特定的department，包含它的Employees，建立一个ViewModel
        //        // 给你departmentId, 帮我寻找第一个满足条件的department记录
        //        var departmentId = int.Parse(department["Id"]);
        //        var departmentInDb = dbContext.Departments
        //                                   .Include("Employees")
        //                                   .FirstOrDefault(dept => dept.Id == departmentId);

        //        // 如果在数据库中找到了对应的记录，则进行下面的操作，即将传入的新的department数据，赋值给数据库中对应的记录
        //        if (departmentInDb != null)
        //        {
        //            departmentInDb.DepartmentName = department["DepartmentName"];
        //            departmentInDb.Location = department["Location"];
        //            departmentInDb.DepartmentHead = department["DepartmentHead"];
        //            // 告诉Entity Framework 将新纪录存入数据库
        //            dbContext.SaveChanges();
        //        }
        //        // 返回到Details View
        //        return RedirectToAction("Index");
        //    }
        //}
        #endregion
    }
}

MVCTutorial/MVCTutorial.Web/Views/Department/Create.cshtml
@model MVCTutorial.Web.Models.Department

@{
    ViewBag.Title = "Create";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm("Create", "Department", FormMethod.Post)) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Department</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.DepartmentName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DepartmentName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DepartmentName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.DepartmentHead, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DepartmentHead, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DepartmentHead, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

MVCTutorial/MVCTutorial.Web/Views/Department/Details.cshtml
@model MVCTutorial.Web.Models.Department

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Department</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DepartmentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartmentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepartmentHead)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartmentHead)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employees)
        </dt>

        <dd>
            <table class="table table-hover">
                @{
                    foreach (var employee in Model.Employees)
                    {
                        <tr>
                            <td style="padding-right:20px;">@employee.Name</td>
                            <td style="padding-right:20px;">@employee.Gender</td>
                            <td style="padding-right:20px;">@employee.Salary</td>
                        </tr>
                    }
                }
            </table>
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVCTutorial/MVCTutorial.Web/Views/Department/Edit.cshtml
@model MVCTutorial.Web.Models.Department

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Department", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Department</h4>
        <hr />
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartmentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartmentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentHead, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartmentHead, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartmentHead, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVCTutorial/MVCTutorial.Web/Views/Department/Index.cshtml
@model IEnumerable<MVCTutorial.Web.Models.Department>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    <!-- 这个ActionLink建立的超链接，会生成/Department/Create这个超链接，用于创建新的Departmet对象 -->
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DepartmentName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepartmentHead)
        </th>
        <th></th>
    </tr>

    @foreach (var department in Model)
    {
        using (@Html.BeginForm("Delete", "Department", new { id = department.Id }, FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => department.DepartmentName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => department.Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => department.DepartmentHead)
                </td>
                <td>
                    <!-- 这个ActionLink建立的超链接，会生成/Department/Edit这个超链接，用于修改一个现存的Departmet对象 -->
                    @Html.ActionLink("Edit", "Edit", new { id = department.Id }) |
                    <!-- 这个ActionLink建立的超链接，会生成/DepartmentDetails这个超链接，用于查看一个现存的Departmet对象的详细情况，包括Employees -->
                    @Html.ActionLink("Details", "Details", new { id = department.Id }) |
                    <input type="submit" value="Delete" onclick='return confirm("Are you sure you want to delete this record?")' />
                </td>
            </tr>
        }
    }
</table>